# Generated by Django 4.0.3 on 2022-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Watch', 'Watch'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Not Started', 'Not Started')], max_length=20),
        ),
    ]
