# Generated by Django 4.0.3 on 2022-04-02 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_alter_project_description_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['create_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Watch', 'Watch')], max_length=20),
        ),
    ]
