# Generated by Django 4.0.3 on 2022-04-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0004_team_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(to='project_management_app.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Not Started', 'Not Started'), ('Complete', 'Complete'), ('In Progress', 'In Progress')], max_length=20),
        ),
    ]
